version: "3.4"

services:
    app:
        image: p5sightseer-server
        container_name: p5sightseer
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - target: 5180
              published: 5180
              protocol: tcp
        volumes:
            - ./worlds:/home/steam/Games/Sightseer/Worlds
